# Generated by Django 5.0.7 on 2024-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='expected_output',
            field=models.TextField(default='Expected output not provided'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='test_code',
            field=models.TextField(default='print("Test code not provided")'),
        ),
        migrations.AddField(
            model_name='solution',
            name='language',
            field=models.CharField(choices=[('python3', 'Python 3'), ('javascript', 'JavaScript')], default='python3', max_length=50),
        ),
    ]
